package vu.mif.myBatis.DAO;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.mif.myBatis.model.Armyunit;
@Mapper
public interface ArmyunitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARMYUNIT
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARMYUNIT
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    int insert(Armyunit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARMYUNIT
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    Armyunit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARMYUNIT
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    List<Armyunit> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ARMYUNIT
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    int updateByPrimaryKey(Armyunit record);

}