package vu.mif.myBatis.DAO;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.mif.myBatis.model.Mission;
import vu.mif.myBatis.model.Soldier;

@Mapper
public interface MissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MISSION
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    int deleteByPrimaryKey(Long missionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MISSION
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    int insert(Mission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MISSION
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    Mission selectByPrimaryKey(Long missionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MISSION
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    List<Mission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MISSION
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    int updateByPrimaryKey(Mission record);
    List<Mission> selectByUnit(Long id);
}