package vu.mif.myBatis.DAO;

import java.util.List;

import org.apache.ibatis.annotations.Select;
import org.mybatis.cdi.Mapper;
import vu.mif.myBatis.model.Armyunit;
import vu.mif.myBatis.model.Soldier;

import javax.enterprise.context.RequestScoped;
@Mapper
public interface SoldierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SOLDIER
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SOLDIER
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    int insert(Soldier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SOLDIER
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    Soldier selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SOLDIER
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    List<Soldier> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SOLDIER
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    int updateByPrimaryKey(Soldier record);

    List<Soldier> selectByUnit(Long id);
}