package vu.mif.myBatis.model;

import java.util.ArrayList;
import java.util.List;

public class Armyunit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARMYUNIT.ID
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARMYUNIT.NAME
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARMYUNIT.ID
     *
     * @return the value of PUBLIC.ARMYUNIT.ID
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARMYUNIT.ID
     *
     * @param id the value for PUBLIC.ARMYUNIT.ID
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARMYUNIT.NAME
     *
     * @return the value of PUBLIC.ARMYUNIT.NAME
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARMYUNIT.NAME
     *
     * @param name the value for PUBLIC.ARMYUNIT.NAME
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}