package vu.mif.myBatis.model;

public class ArmyunitMission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARMYUNIT_MISSION.ARMYUNITS_ID
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    private Long armyunitsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARMYUNIT_MISSION.MISSIONS_MISSIONID
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    private Long missionsMissionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARMYUNIT_MISSION.ARMYUNITS_ID
     *
     * @return the value of PUBLIC.ARMYUNIT_MISSION.ARMYUNITS_ID
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    public Long getArmyunitsId() {
        return armyunitsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARMYUNIT_MISSION.ARMYUNITS_ID
     *
     * @param armyunitsId the value for PUBLIC.ARMYUNIT_MISSION.ARMYUNITS_ID
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    public void setArmyunitsId(Long armyunitsId) {
        this.armyunitsId = armyunitsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARMYUNIT_MISSION.MISSIONS_MISSIONID
     *
     * @return the value of PUBLIC.ARMYUNIT_MISSION.MISSIONS_MISSIONID
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    public Long getMissionsMissionid() {
        return missionsMissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARMYUNIT_MISSION.MISSIONS_MISSIONID
     *
     * @param missionsMissionid the value for PUBLIC.ARMYUNIT_MISSION.MISSIONS_MISSIONID
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    public void setMissionsMissionid(Long missionsMissionid) {
        this.missionsMissionid = missionsMissionid;
    }
}