package vu.mif.myBatis.model;

public class Mission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MISSION.MISSIONID
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    private Long missionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MISSION.COUNTRY
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MISSION.NAME
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MISSION.MISSIONID
     *
     * @return the value of PUBLIC.MISSION.MISSIONID
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    public Long getMissionid() {
        return missionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MISSION.MISSIONID
     *
     * @param missionid the value for PUBLIC.MISSION.MISSIONID
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    public void setMissionid(Long missionid) {
        this.missionid = missionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MISSION.COUNTRY
     *
     * @return the value of PUBLIC.MISSION.COUNTRY
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MISSION.COUNTRY
     *
     * @param country the value for PUBLIC.MISSION.COUNTRY
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MISSION.NAME
     *
     * @return the value of PUBLIC.MISSION.NAME
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MISSION.NAME
     *
     * @param name the value for PUBLIC.MISSION.NAME
     *
     * @mbg.generated Mon Apr 20 02:01:13 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}