package vu.mif.myBatis.model;

import javax.persistence.Entity;

public class Soldier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SOLDIER.ID
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SOLDIER.NAME
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SOLDIER.ARMYUNIT_ID
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    private Long armyunitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SOLDIER.ID
     *
     * @return the value of PUBLIC.SOLDIER.ID
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SOLDIER.ID
     *
     * @param id the value for PUBLIC.SOLDIER.ID
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SOLDIER.NAME
     *
     * @return the value of PUBLIC.SOLDIER.NAME
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SOLDIER.NAME
     *
     * @param name the value for PUBLIC.SOLDIER.NAME
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SOLDIER.ARMYUNIT_ID
     *
     * @return the value of PUBLIC.SOLDIER.ARMYUNIT_ID
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    public Long getArmyunitId() {
        return armyunitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SOLDIER.ARMYUNIT_ID
     *
     * @param armyunitId the value for PUBLIC.SOLDIER.ARMYUNIT_ID
     *
     * @mbg.generated Sat Apr 18 12:21:35 EEST 2020
     */
    public void setArmyunitId(Long armyunitId) {
        this.armyunitId = armyunitId;
    }
}